### ISSUE TITLE
nVidia docker 설치 오류

### ISSUE THREAD

**Issue by edimoon777** [pineland/pineland.github.com#2]
nVidia Docker 설치 후 확인해보니 아래와 같이 에러가 뜨네요.
------------------------------------------------------------------------------------------------------------------------------
jungho@jungho-Inspiron-7577:~$ sudo docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
Unable to find image 'nvidia/cuda:latest' locally
latest: Pulling from nvidia/cuda
473ede7ed136: Pull complete 
c46b5fa4d940: Pull complete 
93ae3df89c92: Pull complete 
6b1eed27cade: Pull complete 
cb5511f09cc0: Pull complete 
4173c1e5c714: Pull complete 
221b05733c9e: Extracting [==================================================>]  472.4MB/472.4MB
221b05733c9e: Pull complete 
564d11654322: Pull complete 
Digest: sha256:2c7a92b1ca05a770addc715ed247c8235f1d9e96b8b032feaa426cd8f4c7535e
Status: Downloaded newer image for nvidia/cuda:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=11642 /var/lib/docker/overlay2/4502ae877d8e3e99019fe76779f873827d214e89369425a3e3cbb950fd95677e/merged]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: brand = tesla\\\\n\\\"\"": unknown.

**Comment by teoac** [comment]
일단 pc 재부팅 해보심이...

**Comment by edimoon777** [comment]
cuda:9.0-base 를 추가하니 아래처럼 나오는데 된 건가요?
-------------------------------------------------------------------------------------------------------
$sudo docker run --runtime=nvidia --rm nvidia/cuda:9.0-base  nvidia-smi
Tue Jan  8 12:55:25 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   48C    P3    18W /  N/A |    343MiB /  6072MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by teoac** [comment]
제대로 나오고 있는 것 아닐까요? 칸이 맞지 않아서 표는 깨졌지만, 위에 실행하신 명령어를 분석해보면, cuda:9.0이 설치된 컨테이너 내에서 nvidia-smi 명령어를 실행시키고 바로 컨테이너를 지우는 명령어로 해석되는데요, 그렇다면 실행이 잘 되고 종료된 것으로 보입니다. (표가 깨져서 표 내용이 옳은 것인지는 잘 모르겠네요. ㅎㅎㅎ)

만약 제대로 작동한거라면 어제 에러가 발생한 것은 @edimoon777 님 랩탑에 기본으로 설치된 nvidia driver에서 지원하지 않는 cuda가 설치된 이미지로 컨테이너를 구성하려고 한 것이 원인인 것 같습니다. 에러 구문을 보시면 cuda:latest 라는 부분이 나오는데 이것은 최신 버전을 설치하겠다는 의도로 보이며, 결국 cuda 10.0을 기반으로 하는 이미지를 pull 하겠다는 것이거든요. nvidia 384.xx에서는 cuda 9.0까지 밖에 지원하지 않습니다.

**Comment by edimoon777** [comment]
그럼 cuda9.0 을 쓰면 되는거죠?
감사합니다. ^^*
